// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Kuchulem_Base","status":true,"description":"Adds basics methods used by Kuchulem plugins.","parameters":{}},
{"name":"Kuchulem_ArrayExtensions","status":true,"description":"Extension methods of the Array object.","parameters":{}},
{"name":"Kuchulem_Events","status":true,"description":"Adds and events publisher on specific methods of RMMZ core classes.","parameters":{}},
{"name":"Kuchulem_GameTime","status":true,"description":"Manages in-game time.","parameters":{"minutesVariableId":"1","hoursVariableId":"2","daysVariableId":"3","framesPerMinute":"300","displaySpan":"1"}},
{"name":"Kuchulem_Areas","status":true,"description":"Manages map areas.","parameters":{"dataFile":"Areas.json"}},
{"name":"Kuchulem_MapLighting","status":true,"description":"Manages lightings in a map.","parameters":{"dataFile":"MapsLighting.json"}},
{"name":"Kuchulem_Npcs","status":true,"description":"Manages NPCs and affects them to events in maps.","parameters":{"dataFile":"Npcs.json"}},
{"name":"Kuchulem_Convos","status":true,"description":"Relies on Kuchulem_Npcs plugin to change conversations images.","parameters":{}}
];
